### ISSUE TITLE
Support for python 3.4 and 3.5

### ISSUE THREAD

**Issue by xelia** [kensho-technologies/pytest-annotate#2]
Pyannotate supports Python 3.4 and 3.5 with exception for Python 3.5.1, pytest-annotate also works with my python 3.4.3, but i cant install it from pypi and need to use pip install from git with  --ignore-requires-python at the moment.

**Comment by obi1kenobi** [comment]
Any idea why pip installing from pypi doesn't work for 3.4.3? Is this something that can be fixed easily? I don't think `pytest-annotate` should support a version of python that `PyAnnotate` won't support, because pip will try to install `PyAnnotate` as a dependency and fail.

I'm happy to add support for 3.5 (`!=3.5.1`) for the next release, and I'd also take a PR if you'd like to open one to that effect.

Thanks!

**Comment by xelia** [comment]
Its already working for 3.5 >3.5.1  and i think fixing python_requires would be enough for 3.4

**Comment by obi1kenobi** [comment]
Closed with #3, released in v1.0.1.
